import 'server-only';

import { randomUUID } from 'node:crypto';

import sharp from 'sharp';

import { createAdminClient } from '@/lib/supabase/admin';
import {
  DISPLAY_BUCKET,
  ORIGINALS_BUCKET,
  deleteStoredObjects,
  displayPath,
  originalPath,
} from '@/lib/images/storage';

/**
 * T027 — the image pipeline (FR-007, FR-009, FR-010, FR-011).
 *
 * For each uploaded photo:
 *   1. decode (HEIC included — see T009, verified via `npm run verify:heic`);
 *   2. correct EXIF orientation, or half the phone uploads arrive sideways;
 *   3. store the original untouched, for the designer's own reference (FR-010);
 *   4. write a compressed WebP display variant (FR-009);
 *   5. generate a tiny inline LQIP for the blur placeholder (FR-011);
 *   6. return real pixel dimensions, which the no-layout-shift guarantee depends on
 *      (SC-012) and which are therefore NOT optional.
 *
 * Failure is per-photo and reported, never thrown past the caller: FR-012 requires that
 * one bad file leave the rest of the upload alone, and FR-013a requires the design to be
 * abandoned only if *every* photo fails.
 */

/** Longest edge of the stored display variant. */
const DISPLAY_MAX_EDGE = 2048;
/** LQIP is deliberately tiny — it is inlined into the HTML on every grid render. */
const LQIP_EDGE = 16;

export interface ProcessedPhoto {
  photoId: string;
  originalPath: string;
  displayPath: string;
  blurPlaceholder: string;
  width: number;
  height: number;
}

/** A processed photo tagged with its position in the batch it came from, so the caller can
 *  reunite it with per-photo metadata (alt text) after failures have shifted the indices. */
export interface ProcessedPhotoWithSource extends ProcessedPhoto {
  sourceIndex: number;
}

export interface PhotoInput {
  /** Raw bytes as uploaded. */
  bytes: Buffer;
  /** Original filename, used only to derive the stored extension. */
  filename: string;
}

export type ProcessResult =
  | { ok: true; photo: ProcessedPhoto }
  | { ok: false; filename: string; reason: string };

function extensionFor(filename: string, detectedFormat: string | undefined): string {
  const fromName = filename.split('.').pop()?.toLowerCase();
  if (fromName && /^(jpe?g|png|heic|heif)$/.test(fromName)) return fromName;
  if (detectedFormat === 'heif') return 'heic';
  if (detectedFormat === 'jpeg') return 'jpg';
  return detectedFormat ?? 'bin';
}

/**
 * Processes and stores one photo.
 *
 * `photoId` is generated by the caller so the storage paths can be written before the
 * database row exists — that ordering is what lets a failed upload leave nothing behind
 * (FR-013a).
 */
export async function processAndStorePhoto(
  designId: string,
  photoId: string,
  input: PhotoInput,
): Promise<ProcessResult> {
  const admin = createAdminClient();

  try {
    // `failOn: 'none'` keeps slightly malformed but recoverable phone photos usable
    // rather than rejecting a picture the designer can see fine on her device.
    const pipeline = sharp(input.bytes, { failOn: 'none' }).rotate();

    const metadata = await pipeline.metadata();
    if (!metadata.width || !metadata.height) {
      return { ok: false, filename: input.filename, reason: 'Could not read image dimensions.' };
    }

    const displayBuffer = await pipeline
      .clone()
      .resize({
        width: DISPLAY_MAX_EDGE,
        height: DISPLAY_MAX_EDGE,
        fit: 'inside',
        withoutEnlargement: true,
      })
      .webp({ quality: 82, effort: 4 })
      .toBuffer({ resolveWithObject: true });

    const lqipBuffer = await pipeline
      .clone()
      .resize({ width: LQIP_EDGE, height: LQIP_EDGE, fit: 'inside' })
      .webp({ quality: 40 })
      .toBuffer();

    const ext = extensionFor(input.filename, metadata.format);
    const origPath = originalPath(designId, photoId, ext);
    const dispPath = displayPath(designId, photoId);

    // Original first: if this fails there is nothing to clean up.
    const { error: originalError } = await admin.storage
      .from(ORIGINALS_BUCKET)
      .upload(origPath, input.bytes, {
        contentType: metadata.format ? `image/${metadata.format}` : 'application/octet-stream',
        upsert: true,
      });
    if (originalError) {
      return { ok: false, filename: input.filename, reason: originalError.message };
    }

    const { error: displayError } = await admin.storage
      .from(DISPLAY_BUCKET)
      .upload(dispPath, displayBuffer.data, { contentType: 'image/webp', upsert: true });
    if (displayError) {
      // Roll back the original so a half-stored photo cannot become a broken tile.
      await admin.storage.from(ORIGINALS_BUCKET).remove([origPath]);
      return { ok: false, filename: input.filename, reason: displayError.message };
    }

    return {
      ok: true,
      photo: {
        photoId,
        originalPath: origPath,
        displayPath: dispPath,
        blurPlaceholder: `data:image/webp;base64,${lqipBuffer.toString('base64')}`,
        // Dimensions of the DISPLAY variant, since that is what gets rendered and what
        // must match the reserved box.
        width: displayBuffer.info.width,
        height: displayBuffer.info.height,
      },
    };
  } catch (error) {
    const reason = error instanceof Error ? error.message : 'Unknown image processing failure.';
    return { ok: false, filename: input.filename, reason };
  }
}

/**
 * T044 — process a batch, surviving individual failures.
 *
 * FR-012 requires one bad file to leave the rest of the upload alone, and FR-013a requires
 * the design to be abandoned only when *every* photo fails. Both need the same shape:
 * successes and failures side by side, nothing thrown.
 *
 * Photos are processed sequentially rather than with `Promise.all`. `sharp` decoding a
 * 25 MB HEIC is memory-hungry, and eight of them at once is how a serverless function
 * gets OOM-killed mid-upload — which is precisely the interrupted upload this task exists
 * to make survivable.
 */
export async function processPhotoBatch(
  designId: string,
  inputs: readonly PhotoInput[],
): Promise<{
  processed: ProcessedPhotoWithSource[];
  failures: Array<{ filename: string; reason: string }>;
}> {
  const processed: ProcessedPhotoWithSource[] = [];
  const failures: Array<{ filename: string; reason: string }> = [];

  for (const [sourceIndex, input] of inputs.entries()) {
    const photoId = randomUUID();
    const result = await processAndStorePhoto(designId, photoId, input);
    if (result.ok) processed.push({ ...result.photo, sourceIndex });
    else failures.push({ filename: result.filename, reason: result.reason });
  }

  return { processed, failures };
}

/**
 * T044 — undo stored objects when the design they belong to is not going to exist.
 *
 * The interrupted-upload story turns on ordering. Files are written before the `design`
 * row, because the storage path contains the design id. So every path that abandons the
 * create — no photo processed, the insert rejected, the request cancelled — has to remove
 * what was already written, or the bucket accumulates orphans that no row references and
 * nothing will ever clean up.
 *
 * Failures here are collected, not thrown: the caller is already on an error path and a
 * storage hiccup must not mask the original reason the design was abandoned.
 */
export async function discardProcessedPhotos(
  photos: readonly ProcessedPhoto[],
): Promise<{ removed: number; errors: string[] }> {
  if (photos.length === 0) return { removed: 0, errors: [] };

  return deleteStoredObjects(
    photos.map((p) => p.originalPath),
    photos.map((p) => p.displayPath),
  );
}
